### ISSUE TITLE
Permissions FTP

### ISSUE THREAD

**Issue by mrdonthave** [lucanos/WordPress-Remote-Installer#1]
Hi!

if i install WP and all the Plugins and themes with this script, the rights seems to be okay (e.g. 755), but the group and user of files and directories does deny to edit/move/delete any of this.

Is this an issue of my server-configuration or should they bey an option to chown processed files through this script?

thanks,
Christian

**Comment by lucanos** [comment]
I have not seen this behavior before. Considering the Remote Installer is run by the Apache User, I would expect any files and folders which are subsequently generated would belong to that same User.

It may be that your FTP User does not have permissions to modify/delete files created by your Apache User. Which would be a Server Config thing...

**Comment by mrdonthave** [comment]
thanks for your answer.

i've suspect that.
but at shared hosting i have no options to change the users for this operations.
but WordPress itself installs plugins and themes as/with the ftp-user. how does this work? is there maybe a work to do this in a similar way? do you have any ideas about?

thanks!

**Comment by mrdonthave** [comment]
btw. i have seen this behavior often at such kind of operations in plugins like duplicator ... :-)

**Comment by lucanos** [comment]
Unfortunately, this is not really something which can be solved by this script.
Sorry.
